//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 04:13:55 PM CET 
//


package eu.europa.esig.dss.ws.impl;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.esig.dss.web.log package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.dss.web.log
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LinsignLogs }
     * 
     */
    public LinsignLogs createLinsignLogs() {
        return new LinsignLogs();
    }

    /**
     * Create an instance of {@link LinsignLogs.Log }
     * 
     */
    public LinsignLogs.Log createLinsignLogsLog() {
        return new LinsignLogs.Log();
    }

    /**
     * Create an instance of {@link SignPolicies.Policy.Signature }
     * 
     */
    public SignPolicies.Policy.Signature createSignPoliciesPolicySignature() {
        return new SignPolicies.Policy.Signature();
    }

    /**
     * Create an instance of {@link SignPolicies.Policy.Document }
     * 
     */
    public SignPolicies.Policy.Document createSignPoliciesPolicyDocument() {
        return new SignPolicies.Policy.Document();
    }

    /**
     * Create an instance of {@link SignPolicies.Policy }
     * 
     */
    public SignPolicies.Policy createSignPoliciesPolicy() {
        return new SignPolicies.Policy();
    }

    /**
     * Create an instance of {@link SignPolicies }
     * 
     */
    public SignPolicies createSignPolicies() {
        return new SignPolicies();
    }
    
}
